# Generated by Django 6.0.2 on 2026-02-23 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='qtd_estoque',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.AddField(
            model_name='produto',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
