# Generated by Django 6.0.2 on 2026-02-23 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_descricao_categoria_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
